{% set name = "tango-gateway" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tango_gateway-{{ version }}.tar.gz
  sha256: a95de03b58469cd63d7ff0dc2db7fcd0dd5bc6ffd0f035cb90cd56d66a46142b

build:
  entry_points:
    - tango-gateway = tangogateway:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - aiozmq
    - python >=3.9

test:
  imports:
    - tangogateway
  commands:
    - pip check
    - tango-gateway --help
  requires:
    - pip

about:
  home: https://gitlab.com/MaxIV/tango-gateway
  summary: A Tango gateway server
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - initfve
    - beenje
